name: Action test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-linux.yaml'
      - 'action.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run STK CLI installation
        uses: stack-spot/stk-cli-action@main
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}

      - name: Get Token
        run: |
          curl --location 'https://idm.stackspot.com/realms/stackspot-internal/protocol/openid-connect/token' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'client_id=${{ inputs.client_id }}' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode 'client_secret=${{ inputs.client_key }}'
        shell: bash

      - name: Fetch Endpoint
        run: |
          curl -s "https://viacep.com.br/ws/06727010/json/" > cep_data.json
          cat cep_data.json  # Apenas para visualizar o resultado no log.
