name: 'Runtime Deploy'

description: 'Runtime Deploy Action'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account client realm
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Get Token
      shell: bash
      run: |
        TOKEN_OUTPUT=$(curl --location --request POST \
        'https://idm.stackspot.com/realms/${{ inputs.realm }}/protocol/openid-connect/token' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode 'client_id=${{ inputs.client_id }}' \
        --data-urlencode 'grant_type=client_credentials' \
        --data-urlencode 'client_secret=${{ inputs.client_key }}')
      
    - name: Fetch Endpoint
      shell: bash
      run: |
        "Would call Runtime API through curl: POST /run/deploy/app/self-hosted"
        JSON = $(cat ${{ github.action_path }}/tasks.json)
        echo "JSON: $JSON"

branding:
    icon: 'terminal'
    color: 'gray-dark'